version: '3.5'
services:
  mariadb:
    image: mariadb:10.3
    container_name: xfacedb
    hostname: xfacedb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./resources/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
