version: '3.5'
services:
  mariadb:
    image: mariadb:10.9
    container_name: mariadb_xface
    hostname: mariadb_xface
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./resources/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
