version: '3.6'

volumes:
  mariadb-data:
services:
  mariadb:
    image: mariadb:10.8.2
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
      - ./config/10-custom.cnf:/etc/mysql/mariadb.conf.d/10-custom.cnf
      - ./resources/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: test: mysqladmin ping -u root --password=root
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8083:8080