version: '3.6'
volumes:
  mariadb-data:
    driver: local
  account-service-data:
    driver: local
  redis-data:
    driver: local

services:
  mariadb:
    image: mariadb:10.8.2
    container_name: mariadb_xface_2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./config/10-custom.cnf:/etc/mysql/mariadb.conf.d/10-custom.cnf
      - ./resources/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis-data:/data

  account_service:
    image: account_service:latest
    container_name: account_service
    depends_on:
      - mariadb
      - redis
    ports: 
      - 172.21.100.174:9082:9082
    volumes:
      - account-service-data:/root/.vscode-server/extensions:rw
    environment: 
      DYNACONF_MARIADB_HOST: mariadb
      DYNACONF_MARIADB_PORT: 3306
      DYNACONF_MARIADB_NAME: xface_system
      DYNACONF_REDIS_HOST: redis
      DYNACONF_REDIS_PORT: 6379
      DYNACONF_TOKEN_EXPIRES: 14400
      DYNACONF_REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      DYNACONF_SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7